// File generated by FlutterFire CLI.
// This is a minimal configuration for Firebase
// You should run `flutterfire configure` to generate proper configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChojLYGhblVCeRwH3lePS1F4WOB34PR-k',
    appId: '1:517411111908:web:c6e5c6f04daa0ff0f67df1',
    messagingSenderId: '517411111908',
    projectId: 'to-do-list-app-98e44',
    authDomain: 'to-do-list-app-98e44.firebaseapp.com',
    storageBucket: 'to-do-list-app-98e44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1FRp9n86slMGGpSVBME3FeZop2Dv8aLU',
    appId: '1:517411111908:android:be62ee4ef3eddd92f67df1',
    messagingSenderId: '517411111908',
    projectId: 'to-do-list-app-98e44',
    storageBucket: 'to-do-list-app-98e44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHAe-9YpPKQF9e-k2jhCtA8suPYI1aaFI',
    appId: '1:517411111908:ios:07065a144b7ae996f67df1',
    messagingSenderId: '517411111908',
    projectId: 'to-do-list-app-98e44',
    storageBucket: 'to-do-list-app-98e44.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHAe-9YpPKQF9e-k2jhCtA8suPYI1aaFI',
    appId: '1:517411111908:ios:07065a144b7ae996f67df1',
    messagingSenderId: '517411111908',
    projectId: 'to-do-list-app-98e44',
    storageBucket: 'to-do-list-app-98e44.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChojLYGhblVCeRwH3lePS1F4WOB34PR-k',
    appId: '1:517411111908:web:26f19df8d39e25aef67df1',
    messagingSenderId: '517411111908',
    projectId: 'to-do-list-app-98e44',
    authDomain: 'to-do-list-app-98e44.firebaseapp.com',
    storageBucket: 'to-do-list-app-98e44.firebasestorage.app',
  );

}